MyELearningProject/Controllers/AdminLayoutController.cs
using MyELearningProject.DAL.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyELearningProject.Controllers
{
    public class AdminLayoutController : Controller
    {
		ELearningContext c = new ELearningContext();
		public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }

        public PartialViewResult PartialScript()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
			var values = Session["AdminMail"].ToString();
			ViewBag.mail = Session["AdminMail"];
			ViewBag.name = c.admins.Where(x => x.adminMail == values.ToString())
				.Select(y => y.kullaniciAdi).FirstOrDefault();
			return PartialView();
        }
        public PartialViewResult PartialPageRowTittle()
        {
            return PartialView();
        }
        public PartialViewResult PartialPreLoader()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }

    }
}

MyELearningProject/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead","AdminLayout")

<body class="fix-header fix-sidebar card-no-border">

    @Html.Action("PartialPreLoader", "AdminLayout")

    <div id="main-wrapper">

        @Html.Action("PartialNavbar", "AdminLayout")

        @Html.Action("PartialSidebar", "AdminLayout")

        <div class="page-wrapper">

            <div class="container-fluid">

                @Html.Action("PartialPageRowTittle", "AdminLayout")

                @RenderBody()

            </div>

            @Html.Action("PartialFooter", "AdminLayout")

        </div>

    </div>

    @Html.Action("PartialScript", "AdminLayout")
</body>

</html>

MyELearningProject/Views/AdminLayout/PartialFooter.cshtml
<footer class="footer">
    © @DateTime.Now.Year | Tüm Hakları Saklıdır
</footer>

MyELearningProject/Views/AdminLayout/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="~/Templates/material-lite-master/assets/image/png" sizes="16x16" href="~/Templates/material-lite-master/assets/images/favicon.png">
    <title>E-learning Proje</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Templates/material-lite-master/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Templates/material-lite-master/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="~/Templates/material-lite-master/css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<!--<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
    <!-- Tell the browser to be responsive to screen width -->
    <!--<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">-->
    <!-- Favicon icon -->
    <!--<link rel="icon" type="image/png" sizes="16x16" href="~/Templates/material-lite-master/css/assets/images/favicon.png">
    <title>ELearning Admin Paneli</title>-->
    <!-- Bootstrap Core CSS -->
    <!--<link href="~/Templates/material-lite-master/css/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->
    <!-- Custom CSS -->
    <!--<link href="~/Templates/material-lite-master/css/css/style.css" rel="stylesheet">-->
    <!-- You can change the theme colors from here -->
    <!--<link href="~/Templates/material-lite-master/css/colors/blue.css" id="theme" rel="stylesheet">-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<!--</head>-->

MyELearningProject/Views/AdminLayout/PartialNavbar.cshtml
<header class="topbar">
    <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">

        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon --><b>
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Light Logo icon -->
                    <img src="~/Templates/material-lite-master/assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text --><span>

                    <!-- Light Logo text -->
                    <img src="~/Templates/material-lite-master/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                </span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto mt-md-0">
                <!-- This is  -->
                <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item hidden-sm-down search-box">
                    <a class="nav-link hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search">
                        <input type="text" class="form-control" placeholder="Search & enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
            <ul class="navbar-nav my-lg-0">
                <!-- ============================================================== -->
                <!-- Profile -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/Templates/material-lite-master/assets/images/users/1.jpg" alt="user" class="profile-pic m-r-10" />@ViewBag.name</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

MyELearningProject/Views/AdminLayout/PartialPageRowTittle.cshtml
<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor m-b-0 m-t-0">Dashboard</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Anasayfa</a></li>
            <li class="breadcrumb-item active">@ViewBag.tittle </li>
        </ol>
    </div>
    @*<div class="col-md-7 col-4 align-self-center">
        <a href="#" class="btn waves-effect waves-light btn-danger pull-right hidden-sm-down">Raporları İndir</a>
    </div>*@
</div>

MyELearningProject/Views/AdminLayout/PartialPreLoader.cshtml
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
</div>

MyELearningProject/Views/AdminLayout/PartialScript.cshtml
<script src="~/Templates/material-lite-master/assets/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="~/Templates/material-lite-master/assets/plugins/bootstrap/js/tether.min.js"></script>
<script src="~/Templates/material-lite-master/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="~/Templates/material-lite-master/js/jquery.slimscroll.js"></script>
<!--Wave Effects -->
<script src="~/Templates/material-lite-master/js/waves.js"></script>
<!--Menu sidebar -->
<script src="~/Templates/material-lite-master/js/sidebarmenu.js"></script>
<!--stickey kit -->
<script src="~/Templates/material-lite-master/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
<!--Custom JavaScript -->
<script src="~/Templates/material-lite-master/js/custom.min.js"></script>

MyELearningProject/Views/AdminLayout/PartialSidebar.cshtml
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li>
                    <a class="waves-effect waves-dark" href="/Default/Index/" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Siteye Git</span></a>
                </li>

                <li>
                    <a class="waves-effect waves-dark" href="/Category/Index/" aria-expanded="false"><i class="mdi mdi-table"></i><span class="hide-menu">Kategoriler</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Instructor/InstructorList/" aria-expanded="false"><i class="mdi mdi-school"></i><span class="hide-menu">Eğitmenler</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Student/StudentList/" aria-expanded="false"><i class="mdi mdi-book-open"></i><span class="hide-menu">Öğrenciler</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Testimonial/TestimonialList/" aria-expanded="false"><i class="mdi mdi-earth"></i><span class="hide-menu">Referanslar </span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Course/CourseList/" aria-expanded="false"><i class="mdi mdi-book-open-variant"></i><span class="hide-menu"> Kurslar</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/About/AboutList/" aria-expanded="false"><i class="mdi mdi-help-circle"></i><span class="hide-menu">Hakkımızda</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Communucation/communucationList/" aria-expanded="false"><i class="mdi mdi-contacts"></i><span class="hide-menu"> İletişim Bilgilerim</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Contact/contactList/" aria-expanded="false"><i class="mdi mdi-contacts"></i><span class="hide-menu"> Gelen Mesajlar</span></a>
                </li>
                <li>
                    <a class="waves-effect waves-dark" href="/Review/reviewList/" aria-expanded="false"><i class="mdi mdi-access-point-network"></i><span class="hide-menu"> Puanlama</span></a>
                </li>

            </ul>
            @*<div class="text-center m-t-30">
                <a href="https://themewagon.com/themes/material-bootstrap-4-free-admin-template/" class="btn waves-effect waves-light btn-warning hidden-md-down">Download Now</a>
            </div>*@
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    <div class="sidebar-footer">
        <!-- item--><a href="" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
        <!-- item--><a href="" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
        <!-- item--><a href="" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
    </div>
    <!-- End Bottom points-->
</aside>